name: banananina
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.3
  shared_preferences: ^0.5.3+4
  firebase_messaging: ^5.1.6
  firebase_crashlytics: ^0.1.0+3

flutter_icons:
  image_path: "assets/banananina_icon_ios.png" 
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/banner_-_warm_fuzzy_feeling.jpg
   - assets/images/sept-accessories.jpg
   - assets/images/sept-announce-sell-2.jpg
   - assets/images/sept-bags.jpg
   - assets/images/sept-designer.jpg
   - assets/images/sept-men.jpg
   - assets/images/sept-new-in.jpg
   - assets/images/sept-preloved.jpg
   - assets/images/sept-sale.jpg
   - assets/images/sept-shoes.jpg
   - assets/icon/icon-bag.png
   - assets/icon/icon-search.png
   - assets/banananina_logo_mobile.png
   - assets/banananina_icon_ios.png
   - assets/images/sept-gift-wraping.jpg
   - assets/images/sept-under-3-mio.jpg
   - assets/images/sept-preloved-big.jpg
   - assets/images/sept-minis.jpg
   - assets/images/sept-brand-we-love.gif
   - assets/images/sept-preorder.jpg
   - assets/images/sept-totebags.jpg
   - assets/images/sept-crossbody.jpg
   - assets/images/sept-shoulder.jpg
   - assets/images/sept-wallets.jpg
   - assets/images/sept-watches.jpg
   - assets/images/sept-shoes-2.jpg
   - assets/images/00548556_m.jpg
   - assets/images/00548549_m.jpg
   - assets/images/00548532_m.jpg
   - assets/images/00548525_m.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/josefin_sans/JosefinSans-Regular.ttf
        - asset: assets/fonts/josefin_sans/JosefinSans-Italic.ttf
          style: italic
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/nanum_myeongjo/NanumMyeongjo-Regular.ttf
        - asset: assets/fonts/nanum_myeongjo/NanumMyeongjo-Bold.ttf
          weight: 700
    - family:  MyCustomFont
      fonts:
        - asset: assets/fonts/custom/MyCustomFont.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
